/*
STUDENT NUMBER: 215907876

ASSIGNMENT NUMBER : FA/DATT4950M / GS/DIGM5950M Assignment 03

NAME: PHILIP MICHALOWSKI

TITLE: OVERGROWN

INTERACTIONS: The shader mostly illustrates particles and Ising automata
collaborative potential. There is no interaction to be made by human however
there are quite a few possible modifications
- speed modifications on the particle side
- modification of uv values and timing in the automata buffer
- modification of self state in the automata buffer
- rotation matrix in common to get more unexpected particle turns
- different buffer outputs in the image buffer

DESCRIPTION: Overgrown - Modified Lecture Particle system (Wakefield,
https://www.shadertoy.com/view/7ff3RX) and Ising cellular automata model
(Wakefield, https://www.shadertoy.com/view/33yyzc) aim to show an ability how
two systems can modify each other with the states creating generative textures
based on their internal states and randomness. The particle system follows the
probability map of the Ising model morphed by the perlin noise (Gustavson,
https://gist.github.com/patriciogonzalezvivo/670c22f3966e662d2f83). The automata
based on the timing records random values of the wandering particles saved in
the texture and use it to create a new generated by the particles probability
field. This cycle of generative texture loops over.

It's definitely interesting to see the particle, perlin noise and automata
interactions. Each phase the particles wander around the static probability
field and then are being sucked by the perlin noise field to once again get on
the probability field tracks. Then the random overgrowth happens and the
particles form a new probability field by randomly wandering around. When I was
doing this work it was resembling a blood vessels in the leaf (new way to create
a heart tissue)(National Geographic, https://www.youtube.com/watch?v=x4KS6NyFo3Y) 
The growth is similar to some of the plant growth timelapses that I was watching 
before the project (timelapselop, https://www.youtube.com/shorts/6rr6xd9-Ad4). 
The system doesn't create a long term behaviour but rather generative texture 
within the 32 seconds phase. Despite that the effect is quite different after the initial phase.

TECHNICAL REALIZATION : I started with the particle shader (Wakefield,
https://www.shadertoy.com/view/7ff3RX) and I tried to modify speed, turn
parameters and particle generation code to understand how it works. After
understanding how particles are being attracted to colors on the textures, I
used the lecture Ising cellular automata (Wakefield,
https://www.shadertoy.com/view/33yyzc) because it seemed to be interesting when
it creates a green probability path between the patches of red values combined
with temperature. Same as the circle on the particles lecture shader
(Wakefield, https://www.shadertoy.com/view/7ff3RX) I tried to attract the
particle to perlin noise emphasized probability as a morph the temperature
parameter result and stretch of the red channel boundaries. This created a nice
effect but the particles didn't have any result on the automata system and follow
the perlin generated map.

To address that I created a phase period when the particles are wandering over 8
seconds and they are attracted to probability field for 24 seconds. In the grown
period the automata gets the values from the particle trail buffer and saves it
to create a new pattern in the red channel. Then that pattern morphed by the
perlin noise and used as a density attractor field.

What didn't work is - I tried to create a perlin noise attraction based on the
particles forces. I tried to reduce the speed of the particle based on the noise
to cluster them together. I tried to count particles in the region to attract
more particles to that spot but none of those worked - so I stuck to the
perlin noise.

FUTURE EXTENSIONS: It would be interesting to see the particles density based on
the regional count to replace perlin noise. I believe that it's interesting to
eliminate all of the external forces and use what we have in the system. Also
other idea is to adjust the system so that particles behave more fluid like so they
follow the trails to the noise - like being sucked in to the external force and
then released. It's easily achievable with perlin but using the particles system
force and its attraction is quite a challenge as well as a good idea for the
future.

*/

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
  vec2 uv = fragCoord / iResolution.xy;
  // Particle Control
  vec4 A = texture(iChannel0, uv);
  // Particle Traces
  vec4 B = texture(iChannel1, uv);
  // Ising Automata
  vec4 C = texture(iChannel2, uv);

  // Output to screen
  // Multiplication by 0.15 of the automata channel gives nice transparency
  // and give room for particle to show its movement
  fragColor = 0.15 * C * B;
  // Another variant with stronger colors
  // fragColor = 0.15*C*0.15*C*B;
  // To check how the probability field changes
  // fragColor = C;
}